# =============================================================
# Codemagic CI/CD — "Dumb Shell" Configuration
# =============================================================
# This file lives in the Flutter repo root.
# All per-project customization comes from environment variables
# injected by the trigger-build edge function. No manual edits
# are needed for new projects.
# =============================================================

workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      java: 17
      groups:
        - codemagic_credentials  # keystore, etc.
        vars:
        GRADLE_OPTS: "-Xmx8g -Dorg.gradle.jvmargs=-Xmx8g"

    scripts:
      # 1. Download & set custom launcher icon (if provided)
      - name: Set app icon
        ignore_failure: true
        script: |
          if [ -n "$APP_ICON_URL" ]; then
            echo "Downloading icon from $APP_ICON_URL"
            mkdir -p assets/icon
            curl -L -f -o assets/icon/icon.png "$APP_ICON_URL" || { echo "Failed to download icon — continuing"; exit 0; }
            if grep -q flutter_launcher_icons pubspec.yaml; then
              dart run flutter_launcher_icons || echo "flutter_launcher_icons failed — continuing with default icon"
            else
              echo "flutter_launcher_icons not in pubspec.yaml — skipping"
            fi
          else
            echo "No custom icon URL — using default"
          fi

      # 2. Patch app name in AndroidManifest.xml
      - name: Set app name
        script: |
          if [ -n "$APP_NAME" ]; then
            sed -i '' "s/android:label=\"[^\"]*\"/android:label=\"$APP_NAME\"/" android/app/src/main/AndroidManifest.xml
            echo "App name set to: $APP_NAME"
          fi

      # 3. Patch package ID (applicationId + namespace) in build.gradle.kts
      - name: Set package ID
        script: |
          if [ -n "$APP_PACKAGE_ID" ]; then
            GRADLE_FILE="android/app/build.gradle.kts"
            sed -i '' "s/applicationId = \"[^\"]*\"/applicationId = \"$APP_PACKAGE_ID\"/" "$GRADLE_FILE"
            sed -i '' "s/namespace = \"[^\"]*\"/namespace = \"$APP_PACKAGE_ID\"/" "$GRADLE_FILE"
            echo "Package ID set to: $APP_PACKAGE_ID"
          fi

      # 4. Inject google-services.json for Firebase
      - name: Set up Firebase config
        script: |
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo "$GOOGLE_SERVICES_JSON" | base64 -D > android/app/google-services.json
            echo "google-services.json injected"
          else
            echo "Warning: GOOGLE_SERVICES_JSON not set — Firebase features will not work"
          fi

      # 5. Install dependencies
      - name: Flutter pub get
        script: flutter pub get

      # 6. Build the APK/AAB with the game URL injected
      - name: Build Android
        script: |
          if [ "$ANDROID_BUILD_FORMAT" = "appbundle" ]; then
            flutter build appbundle --dart-define=GAME_URL="$OFFER_URL"
          else
            flutter build apk --dart-define=GAME_URL="$OFFER_URL" --${FLUTTER_BUILD_MODE:-release}
          fi

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab

    publishing:
      scripts:
        - name: Notify webhook
          script: |
            WEBHOOK_URL="${SUPABASE_URL:-https://snwijgxwokcxtciobleu.supabase.co}/functions/v1/codemagic-webhook"
            curl -X POST "$WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -d "{
                \"buildId\": \"$BUILD_ID\",
                \"projectId\": \"$PROJECT_ID\",
                \"status\": \"$CM_BUILD_STEP_STATUS\",
                \"artifactUrl\": \"$CM_ARTIFACT_LINKS\"
              }"
