# =============================================================
# Codemagic CI/CD — "Dumb Shell" Configuration
# =============================================================
# This file lives in the Flutter repo root.
# All per-project customization comes from environment variables
# injected by the trigger-build edge function. No manual edits
# are needed for new projects.
# =============================================================

workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      groups:
        - codemagic_credentials  # keystore, etc.

    scripts:
      # 0. Set up release keystore for signing
      - name: Set up keystore
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/release-key.jks
            echo "storePassword=$CM_KEYSTORE_PASSWORD" > "$CM_BUILD_DIR/android/key.properties"
            echo "keyPassword=$CM_KEY_PASSWORD" >> "$CM_BUILD_DIR/android/key.properties"
            echo "keyAlias=$CM_KEY_ALIAS" >> "$CM_BUILD_DIR/android/key.properties"
            echo "storeFile=$CM_BUILD_DIR/release-key.jks" >> "$CM_BUILD_DIR/android/key.properties"
            echo "Release keystore configured"
            cat "$CM_BUILD_DIR/android/key.properties"
          else
            echo "WARNING: No keystore configured — build will use debug signing"
          fi

      # 1. Download & set custom launcher icon (if provided)
      - name: Set app icon
        ignore_failure: true
        script: |
          if [ -n "$APP_ICON_URL" ]; then
            echo "Downloading icon from $APP_ICON_URL"
            mkdir -p assets/icons
            curl -L -f -o assets/icons/icon.png "$APP_ICON_URL" || { echo "Failed to download icon — continuing"; exit 0; }
            if grep -q flutter_launcher_icons pubspec.yaml; then
              dart run flutter_launcher_icons || echo "flutter_launcher_icons failed — continuing with default icon"
            else
              echo "flutter_launcher_icons not in pubspec.yaml — skipping"
            fi
          else
            echo "No custom icon URL — using default"
          fi

      # 2. Patch app name in AndroidManifest.xml
      - name: Set app name
        script: |
          if [ -n "$APP_NAME" ]; then
            sed -i '' "s/android:label=\"[^\"]*\"/android:label=\"$APP_NAME\"/" android/app/src/main/AndroidManifest.xml
            echo "App name set to: $APP_NAME"
          fi

      # 3. Patch package ID (applicationId + namespace) in build.gradle.kts
      - name: Set package ID
        script: |
          if [ -n "$APP_PACKAGE_ID" ]; then
            GRADLE_FILE="android/app/build.gradle.kts"
            MANIFEST="android/app/src/main/AndroidManifest.xml"

            echo "=== DEBUG: Gradle file contents (namespace line) ==="
            grep -i "namespace" "$GRADLE_FILE" || echo "No namespace line found!"

            # Read the current namespace — try multiple patterns
            ORIGINAL_NS=$(sed -n 's/.*namespace[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$GRADLE_FILE" | head -1)

            # Fallback: try without = (Groovy syntax)
            if [ -z "$ORIGINAL_NS" ]; then
              ORIGINAL_NS=$(sed -n 's/.*namespace[[:space:]]*"\([^"]*\)".*/\1/p' "$GRADLE_FILE" | head -1)
            fi

            # Hardcoded fallback for the known template
            if [ -z "$ORIGINAL_NS" ]; then
              ORIGINAL_NS="com.example.endless_runner"
              echo "WARNING: Could not extract namespace, using fallback: $ORIGINAL_NS"
            fi

            echo "Original namespace: $ORIGINAL_NS"
            echo "New package ID: $APP_PACKAGE_ID"

            # Replace applicationId and namespace in Gradle
            sed -i '' "s/applicationId = \"[^\"]*\"/applicationId = \"$APP_PACKAGE_ID\"/" "$GRADLE_FILE"
            sed -i '' "s/namespace = \"[^\"]*\"/namespace = \"$APP_PACKAGE_ID\"/" "$GRADLE_FILE"

            # Pin MainActivity to the ORIGINAL fully-qualified class name
            # Handle both .MainActivity and already-qualified names
            sed -i '' "s|android:name=\"\.MainActivity\"|android:name=\"$ORIGINAL_NS.MainActivity\"|" "$MANIFEST"

            echo "=== DEBUG: AndroidManifest activity line after patch ==="
            grep "MainActivity" "$MANIFEST"

            echo "Package ID set to: $APP_PACKAGE_ID (MainActivity pinned to $ORIGINAL_NS.MainActivity)"
          fi

      # 4. Inject google-services.json for Firebase
      - name: Set up Firebase config
        script: |
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo "$GOOGLE_SERVICES_JSON" | base64 -D > android/app/google-services.json
            echo "google-services.json injected"
          else
            echo "Warning: GOOGLE_SERVICES_JSON not set — Firebase features will not work"
          fi

      # 5. Set app version
      - name: Set app version
        script: |
          if [ -n "$APP_VERSION_NAME" ] || [ -n "$APP_VERSION_CODE" ]; then
            VER_NAME="${APP_VERSION_NAME:-1.0.0}"
            VER_CODE="${APP_VERSION_CODE:-1}"
            PUBSPEC="pubspec.yaml"
            sed -i '' "s/^version: .*/version: ${VER_NAME}+${VER_CODE}/" "$PUBSPEC"
            echo "Version set to: ${VER_NAME}+${VER_CODE}"
          fi

      # 6. Install dependencies
      - name: Flutter pub get
        script: flutter pub get

      # 7. Build the APK/AAB with the game URL injected
      - name: Build Android
        script: |
          DART_DEFINES="--dart-define=GAME_URL=$OFFER_URL"
          [ -n "$AF_DEV_KEY" ] && DART_DEFINES="$DART_DEFINES --dart-define=AF_DEV_KEY=$AF_DEV_KEY"
          [ -n "$SUPABASE_URL" ] && DART_DEFINES="$DART_DEFINES --dart-define=SUPABASE_URL=$SUPABASE_URL"
          [ -n "$APP_PACKAGE_ID" ] && DART_DEFINES="$DART_DEFINES --dart-define=APP_PACKAGE_ID=$APP_PACKAGE_ID"

          # Always build release APK
          flutter build apk $DART_DEFINES --release --build-name="${APP_VERSION_NAME:-1.0.0}" --build-number="${APP_VERSION_CODE:-1}"

          # Always build AAB for Google Play
          flutter build appbundle $DART_DEFINES --build-name="${APP_VERSION_NAME:-1.0.0}" --build-number="${APP_VERSION_CODE:-1}"

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab

    publishing:
      scripts:
        - name: Notify webhook
          script: |
            WEBHOOK_URL="${SUPABASE_URL:-https://snwijgxwokcxtciobleu.supabase.co}/functions/v1/codemagic-webhook"
            curl -X POST "$WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -d "{
                \"buildId\": \"$BUILD_ID\",
                \"projectId\": \"$PROJECT_ID\",
                \"status\": \"$CM_BUILD_STEP_STATUS\",
                \"artifactUrl\": \"$CM_ARTIFACT_LINKS\"
              }"
