# =============================================================
# Codemagic CI/CD — "Dumb Shell" Configuration
# =============================================================
# This file lives in the Flutter repo root.
# All per-project customization comes from environment variables
# injected by the trigger-build edge function. No manual edits
# are needed for new projects.
# =============================================================

workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      groups:
        - codemagic_credentials  # keystore, etc.

    scripts:
      # 0. Set up release keystore for signing
      - name: Set up keystore
        script: |
          if [ -n "$CM_KEYSTORE" ]; then
            echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/release-key.jks
            echo "storePassword=$CM_KEYSTORE_PASSWORD" > "$CM_BUILD_DIR/android/key.properties"
            echo "keyPassword=$CM_KEY_PASSWORD" >> "$CM_BUILD_DIR/android/key.properties"
            echo "keyAlias=$CM_KEY_ALIAS" >> "$CM_BUILD_DIR/android/key.properties"
            echo "storeFile=$CM_BUILD_DIR/release-key.jks" >> "$CM_BUILD_DIR/android/key.properties"
            echo "Release keystore configured"
            cat "$CM_BUILD_DIR/android/key.properties"
          else
            echo "WARNING: No keystore configured — build will use debug signing"
          fi

      # 1. Download & set custom launcher icon (if provided)
      - name: Set app icon
        ignore_failure: true
        script: |
          if [ -n "$APP_ICON_URL" ]; then
            echo "Downloading icon from $APP_ICON_URL"
            mkdir -p assets/icons
            curl -L -f -o assets/icons/icon.png "$APP_ICON_URL" || { echo "Failed to download icon — continuing"; exit 0; }
            if grep -q flutter_launcher_icons pubspec.yaml; then
              dart run flutter_launcher_icons || echo "flutter_launcher_icons failed — continuing with default icon"
            else
              echo "flutter_launcher_icons not in pubspec.yaml — skipping"
            fi
          else
            echo "No custom icon URL — using default"
          fi

      # 2. Patch app name in AndroidManifest.xml
      - name: Set app name
        script: |
          if [ -n "$APP_NAME" ]; then
            sed -i '' "s/android:label=\"[^\"]*\"/android:label=\"$APP_NAME\"/" android/app/src/main/AndroidManifest.xml
            echo "App name set to: $APP_NAME"
          fi

      # 3. Patch package ID (applicationId + namespace) in build.gradle.kts
      - name: Set package ID
        script: |
          if [ -n "$APP_PACKAGE_ID" ]; then
            GRADLE_FILE="android/app/build.gradle.kts"
            MANIFEST="android/app/src/main/AndroidManifest.xml"

            echo "=== DEBUG: Gradle file contents (namespace line) ==="
            grep -i "namespace" "$GRADLE_FILE" || echo "No namespace line found!"

            # Read the current namespace — try multiple patterns
            ORIGINAL_NS=$(sed -n 's/.*namespace[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "$GRADLE_FILE" | head -1)

            # Fallback: try without = (Groovy syntax)
            if [ -z "$ORIGINAL_NS" ]; then
              ORIGINAL_NS=$(sed -n 's/.*namespace[[:space:]]*"\([^"]*\)".*/\1/p' "$GRADLE_FILE" | head -1)
            fi

            # Hardcoded fallback for the known template
            if [ -z "$ORIGINAL_NS" ]; then
              ORIGINAL_NS="com.example.endless_runner"
              echo "WARNING: Could not extract namespace, using fallback: $ORIGINAL_NS"
            fi

            echo "Original namespace: $ORIGINAL_NS"
            echo "New package ID: $APP_PACKAGE_ID"

            # Replace applicationId and namespace in Gradle
            sed -i '' "s/applicationId = \"[^\"]*\"/applicationId = \"$APP_PACKAGE_ID\"/" "$GRADLE_FILE"
            sed -i '' "s/namespace = \"[^\"]*\"/namespace = \"$APP_PACKAGE_ID\"/" "$GRADLE_FILE"

            # Pin MainActivity to the ORIGINAL fully-qualified class name
            # Handle both .MainActivity and already-qualified names
            sed -i '' "s|android:name=\"\.MainActivity\"|android:name=\"$ORIGINAL_NS.MainActivity\"|" "$MANIFEST"

            echo "=== DEBUG: AndroidManifest activity line after patch ==="
            grep "MainActivity" "$MANIFEST"

            echo "Package ID set to: $APP_PACKAGE_ID (MainActivity pinned to $ORIGINAL_NS.MainActivity)"
          fi

      # 4. Inject google-services.json for Firebase (only if enabled)
      - name: Set up Firebase config
        script: |
          if [ "$APP_USE_FIREBASE" = "true" ]; then
            if [ -n "$GOOGLE_SERVICES_JSON" ]; then
              echo "$GOOGLE_SERVICES_JSON" | base64 -D > android/app/google-services.json
              echo "google-services.json injected"
            else
              echo "Warning: APP_USE_FIREBASE=true but GOOGLE_SERVICES_JSON not set — Firebase features will not work"
            fi
          else
            echo "APP_USE_FIREBASE=false — disabling Firebase Gradle plugins"

            # Comment out Firebase plugins in app-level build.gradle.kts
            APP_GRADLE="android/app/build.gradle.kts"
            if [ -f "$APP_GRADLE" ]; then
              sed -i '' 's|id("com.google.gms.google-services")|//id("com.google.gms.google-services") /* firebase disabled */|g' "$APP_GRADLE"
              sed -i '' 's|id("com.google.firebase.crashlytics")|//id("com.google.firebase.crashlytics") /* firebase disabled */|g' "$APP_GRADLE"
              echo "Commented out Firebase app plugins in $APP_GRADLE"
            fi

            # Comment out Firebase classpath in project-level build.gradle.kts
            PROJ_GRADLE="android/build.gradle.kts"
            if [ -f "$PROJ_GRADLE" ]; then
              sed -i '' 's|.*com.google.gms:google-services.*|// firebase disabled: &|g' "$PROJ_GRADLE"
              sed -i '' 's|.*com.google.firebase:firebase-crashlytics-gradle.*|// firebase disabled: &|g' "$PROJ_GRADLE"
              echo "Commented out Firebase classpath entries in $PROJ_GRADLE"
            fi

            # Fallback: check root build.gradle (Groovy syntax)
            ROOT_GRADLE="android/build.gradle"
            if [ -f "$ROOT_GRADLE" ]; then
              sed -i '' 's|.*com.google.gms:google-services.*|// firebase disabled: &|g' "$ROOT_GRADLE"
              sed -i '' 's|.*com.google.firebase:firebase-crashlytics-gradle.*|// firebase disabled: &|g' "$ROOT_GRADLE"
              echo "Commented out Firebase classpath entries in $ROOT_GRADLE"
            fi

            # Check app/build.gradle (Groovy syntax)
            APP_GRADLE_GROOVY="android/app/build.gradle"
            if [ -f "$APP_GRADLE_GROOVY" ]; then
              sed -i '' "s|apply plugin: 'com.google.gms.google-services'|// firebase disabled: apply plugin: 'com.google.gms.google-services'|g" "$APP_GRADLE_GROOVY"
              sed -i '' "s|apply plugin: 'com.google.firebase.crashlytics'|// firebase disabled: apply plugin: 'com.google.firebase.crashlytics'|g" "$APP_GRADLE_GROOVY"
              echo "Commented out Firebase app plugins in $APP_GRADLE_GROOVY"
            fi
          fi

      # 5. Patch deep link URI scheme in AndroidManifest.xml
      - name: Set URI scheme
        script: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if [ -n "$APP_URI_SCHEME" ]; then
            if grep -q "deep_linking_filter" "$MANIFEST"; then
              sed -i '' "s/android:scheme=\"[^\"]*\"/android:scheme=\"$APP_URI_SCHEME\"/" "$MANIFEST"
              echo "URI scheme updated to: $APP_URI_SCHEME"
            else
              INTENT_BLOCK='            <intent-filter android:label="deep_linking_filter">\n                <action android:name="android.intent.action.VIEW" \/>\n                <category android:name="android.intent.category.DEFAULT" \/>\n                <category android:name="android.intent.category.BROWSABLE" \/>\n                <data android:scheme="'"$APP_URI_SCHEME"'" \/>\n            <\/intent-filter>'
              sed -i '' "/<\/activity>/i\\
          $INTENT_BLOCK
          " "$MANIFEST"
              echo "Deep link intent-filter added with scheme: $APP_URI_SCHEME"
            fi
            echo "=== DEBUG: Manifest intent-filter ==="
            grep -A 6 "deep_linking_filter" "$MANIFEST" || echo "No deep_linking_filter found"
          else
            echo "WARNING: APP_URI_SCHEME not set — deep links will not work"
          fi

      # 6. Set app version
      - name: Set app version
        script: |
          if [ -n "$APP_VERSION_NAME" ] || [ -n "$APP_VERSION_CODE" ]; then
            VER_NAME="${APP_VERSION_NAME:-1.0.0}"
            VER_CODE="${APP_VERSION_CODE:-1}"
            PUBSPEC="pubspec.yaml"
            sed -i '' "s/^version: .*/version: ${VER_NAME}+${VER_CODE}/" "$PUBSPEC"
            echo "Version set to: ${VER_NAME}+${VER_CODE}"
          fi

      # 7. Install dependencies
      - name: Flutter pub get
        script: flutter pub get

      # 8. Build the APK/AAB with the game URL injected
      - name: Build Android
        script: |
          DART_DEFINES="--dart-define=GAME_URL=$OFFER_URL"
          [ -n "$AF_DEV_KEY" ] && DART_DEFINES="$DART_DEFINES --dart-define=AF_DEV_KEY=$AF_DEV_KEY"
          [ -n "$SUPABASE_URL" ] && DART_DEFINES="$DART_DEFINES --dart-define=SUPABASE_URL=$SUPABASE_URL"
          [ -n "$APP_PACKAGE_ID" ] && DART_DEFINES="$DART_DEFINES --dart-define=APP_PACKAGE_ID=$APP_PACKAGE_ID"
          [ -n "$BUILDER_PROJECT_ID" ] && DART_DEFINES="$DART_DEFINES --dart-define=BUILDER_PROJECT_ID=$BUILDER_PROJECT_ID"
          [ -n "$LOADING_PRIMARY_COLOR" ] && DART_DEFINES="$DART_DEFINES --dart-define=LOADING_PRIMARY_COLOR=$LOADING_PRIMARY_COLOR"
          [ -n "$LOADING_SECONDARY_COLOR" ] && DART_DEFINES="$DART_DEFINES --dart-define=LOADING_SECONDARY_COLOR=$LOADING_SECONDARY_COLOR"
          DART_DEFINES="$DART_DEFINES --dart-define=APP_USE_FIREBASE=${APP_USE_FIREBASE:-true}"

          # Always build release APK
          flutter build apk $DART_DEFINES --release --build-name="${APP_VERSION_NAME:-1.0.0}" --build-number="${APP_VERSION_CODE:-1}"

          # Always build AAB for Google Play
          flutter build appbundle $DART_DEFINES --build-name="${APP_VERSION_NAME:-1.0.0}" --build-number="${APP_VERSION_CODE:-1}"

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab

    publishing:
      scripts:
        - name: Notify webhook
          script: |
            WEBHOOK_URL="${SUPABASE_URL:-https://snwijgxwokcxtciobleu.supabase.co}/functions/v1/codemagic-webhook"
            curl -X POST "$WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -d "{
                \"buildId\": \"$BUILD_ID\",
                \"projectId\": \"$PROJECT_ID\",
                \"status\": \"$CM_BUILD_STEP_STATUS\",
                \"artifactUrl\": \"$CM_ARTIFACT_LINKS\"
              }"
